In [1]:
import torch

In [2]:
# allocate a 5*3 matrix.
x = torch.empty(5, 3)
print(x)

tensor([[2.2650e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 8.4079e-36]])


In [3]:
# similar to np.random.rand
x = torch.rand(5, 3)
print(x)

tensor([[0.9799, 0.6090, 0.5228],
        [0.0606, 0.9286, 0.7608],
        [0.3677, 0.6649, 0.5648],
        [0.2041, 0.6822, 0.9959],
        [0.2604, 0.7771, 0.8029]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# create a torch tensor from a list.
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6841, -0.9727,  1.3983],
        [-0.3649, -0.3475,  0.7302],
        [ 0.2039, -0.1942,  0.2423],
        [ 0.4768, -0.2921, -1.9185],
        [-0.7704,  0.0206,  0.5203]])


In [7]:
# size, here is not total elements. And works like matlab.
print(x.size())

torch.Size([5, 3])


In [8]:
# addition.
y = torch.rand(5, 3)
print(x + y)
# OR
print(torch.add(x, y))

tensor([[-0.5802, -0.2807,  1.8055],
        [ 0.1449,  0.6383,  1.2436],
        [ 0.3834,  0.6548,  0.6831],
        [ 0.8765,  0.3142, -1.6997],
        [-0.4795,  0.3410,  1.1770]])
tensor([[-0.5802, -0.2807,  1.8055],
        [ 0.1449,  0.6383,  1.2436],
        [ 0.3834,  0.6548,  0.6831],
        [ 0.8765,  0.3142, -1.6997],
        [-0.4795,  0.3410,  1.1770]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5802, -0.2807,  1.8055],
        [ 0.1449,  0.6383,  1.2436],
        [ 0.3834,  0.6548,  0.6831],
        [ 0.8765,  0.3142, -1.6997],
        [-0.4795,  0.3410,  1.1770]])


In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5802, -0.2807,  1.8055],
        [ 0.1449,  0.6383,  1.2436],
        [ 0.3834,  0.6548,  0.6831],
        [ 0.8765,  0.3142, -1.6997],
        [-0.4795,  0.3410,  1.1770]])


In [11]:
# numpy like indexing
print(x[:, 1])

tensor([-0.9727, -0.3475, -0.1942, -0.2921,  0.0206])


In [12]:
# resizing
# hint: this is used as a flatten layer later.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# the item method converts A shape [1] tensor to scalar.
x = torch.randn(1)
print(x.size())
print(x)
print(x.item())

torch.Size([1])
tensor([1.0100])
1.0100178718566895


In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
# tensor to numpy conversion.
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
# this changes both as memory locations are shared. its just a numpy version of the original.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
# from numpy to torch tensor.
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
  print('cuda is not installed.')

cuda is not installed.
